name: nexus

networks:
  nexus-net:
    driver: bridge

volumes:
  postgres_data: {}
  qdrant_data: {}

services:
  temporal:
    image: temporalio/auto-setup:1.28.1
    restart: unless-stopped
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=nexus
      - POSTGRES_PWD=nexus
      - POSTGRES_SEEDS=postgres
    depends_on:
      - postgres
    ports:
      - "7233:7233"
    networks: [nexus-net]

  temporal-ui:
    image: temporalio/ui:2.39.0
    restart: unless-stopped
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal
    ports:
      - "8088:8080"
    networks: [nexus-net]

  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus
      POSTGRES_DB: nexus
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../migrations/postgres:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [nexus-net]
